<a href="https://colab.research.google.com/github/zuee762/Registration_repo/blob/main/Usedcars.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas --quiet
!pip install numpy --quiet
!pip install matplotlib --quiet
!pip install seaborn --quiet
!pip install sklearn --quiet

  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [2]:
!pip install fg-data-profiling --quiet

Collecting fg-data-profiling
  Downloading fg_data_profiling-4.19.1-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.12.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.0.2)
Collecting minify-html>=0.15.0 (from fg-data-profiling)
  Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from fg-data-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from fg-data-profiling)
  Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from fg-data-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (4.5.2)
Collecting imagehash==4.3.2 (from fg-data-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.9.6)
Collecting dacite<2,>=1.9 (from fg-data-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->fg-data-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->fg-data-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->fg-data-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->fg-data-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->fg-data-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->fg-data-profiling) (2026.2)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->fg-data-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (2026.5.20)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->fg-data-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (3.6.1)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling)
  Downloading puremagic-2.2.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->fg-data-profiling) (1.17.0)
Downloading fg_data_profiling-4.19.1-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.3/400.3 kB 16.3 MB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 16.6 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 28.3 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (679 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 25.6 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 11.7 MB/s eta 0:00:00
Downloading puremagic-2.2.0-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 3.9 MB/s eta 0:00:00
Installing collected packages: minify-html, filetype, puremagic, multimethod, dacite, imagehash, visions, phik, fg-data-profiling
Successfully installed dacite-1.9.2 fg-data-profiling-4.19.1 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-2.2.0 visions-0.8.1

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import data_profiling
from data_profiling import ProfileReport

In [4]:
from google.colab import files

In [5]:
upload = files.upload()

Saving used_cars.csv to used_cars.csv

In [6]:
df = pd.read_csv('used_cars.csv')

In [7]:
#profile = ProfileReport(df, title = 'used cars')
#profile.to_file('used_cars.html')
#files.download('used_cars.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]
 33%|███▎      | 4/12 [00:00<00:00, 21.25it/s]
 67%|██████▋   | 8/12 [00:00<00:00, 25.62it/s]
100%|██████████| 12/12 [00:00<00:00, 26.99it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [8]:
df.shape

(4009, 12)

In [161]:
df.head()

,model_year,milage,accident,clean_title,price,brand_alfa,brand_aston,brand_audi,brand_bentley,brand_bmw,...,brand_volvo,fuel_type_e85 flex fuel,fuel_type_gasoline,fuel_type_hybrid,fuel_type_not supported,fuel_type_plug-in hybrid,fuel_type_unknown,fuel_type_–,transmission_hybrid,transmission_manual
0,2013,51000,1,1,10300,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,2021,34742,1,1,38005,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,2022,22372,0,0,54598,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,2015,88900,0,1,15500,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,2021,9835,0,0,34999,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0

In [160]:
df.tail()

,model_year,milage,accident,clean_title,price,brand_alfa,brand_aston,brand_audi,brand_bentley,brand_bmw,...,brand_volvo,fuel_type_e85 flex fuel,fuel_type_gasoline,fuel_type_hybrid,fuel_type_not supported,fuel_type_plug-in hybrid,fuel_type_unknown,fuel_type_–,transmission_hybrid,transmission_manual
4004,2023,714,0,1,349950,0,0,0,1,0,...,0,0,1,0,0,0,0,0,1,0
4005,2022,10900,0,1,53900,0,0,1,0,0,...,0,0,1,0,0,0,0,0,1,0
4006,2022,2116,0,0,90998,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4007,2020,33000,0,1,62999,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4008,2020,43000,1,1,40000,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0

In [157]:
df.dtypes

brand           string[python]
model_year               int64
milage                   int64
fuel_type       string[python]
transmission    string[python]
accident                 int64
clean_title              int64
price                    int64
dtype: object

In [163]:
df.describe()

,model_year,milage,accident,clean_title,price,brand_alfa,brand_aston,brand_audi,brand_bentley,brand_bmw,...,brand_volvo,fuel_type_e85 flex fuel,fuel_type_gasoline,fuel_type_hybrid,fuel_type_not supported,fuel_type_plug-in hybrid,fuel_type_unknown,fuel_type_–,transmission_hybrid,transmission_manual
count,3942.000000,3942.000000,3942.000000,3942.000000,3.942000e+03,3942.000000,3942.000000,3942.000000,3942.000000,3942.000000,...,3942.000000,3942.000000,3942.000000,3942.000000,3942.000000,3942.000000,3942.000000,3942.000000,3942.000000,3942.000000
mean,2015.846525,63794.514713,0.245307,0.849569,4.502109e+04,0.004820,0.002283,0.050736,0.008371,0.094622,...,0.009386,0.035008,0.829782,0.049214,0.000507,0.008625,0.043125,0.004566,0.104008,0.094876
std,5.580673,51619.992352,0.430324,0.357539,7.924598e+04,0.069267,0.047733,0.219485,0.091123,0.292729,...,0.096438,0.183822,0.375872,0.216341,0.022522,0.092482,0.203165,0.067428,0.305310,0.293080
min,2000.000000,100.000000,0.000000,0.000000,2.000000e+03,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2013.000000,22514.500000,0.000000,1.000000,1.780000e+04,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2017.000000,52000.000000,0.000000,1.000000,3.186200e+04,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2020.000000,92953.250000,0.000000,1.000000,4.999900e+04,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2024.000000,405000.000000,1.000000,1.000000,2.954083e+06,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [164]:
df.isnull().sum()

model_year                  0
milage                      0
accident                    0
clean_title                 0
price                       0
                           ..
fuel_type_plug-in hybrid    0
fuel_type_unknown           0
fuel_type_–                 0
transmission_hybrid         0
transmission_manual         0
Length: 70, dtype: int64

In [44]:
df['brand'] = df['brand'].astype('string')
df[['model','milage','fuel_type']] = df[['model','milage','fuel_type']].astype('string')
df[['engine','transmission','accident','clean_title','price']] = df[['engine','transmission','accident','clean_title','price']].astype('string')

In [72]:
df.drop(columns = ['ext_col','int_col'], inplace= True)

KeyError: "['ext_col', 'int_col'] not found in axis"

In [46]:
df['brand'] = df['brand'].str.strip().str.lower()
df['fuel_type'] = df['fuel_type'].str.strip().str.lower()
df['engine'] = df['engine'].str.strip().str.lower()
df['transmission'] = df['transmission'].str.strip().str.lower()
df['accident'] = df['accident'].str.strip().str.lower()
df['clean_title'] = df['clean_title'].str.strip().str.lower()

In [60]:
df['milage'] = df['milage'].str.replace(',','',regex=False).str.replace('mi','',regex=False).str.replace('.','',regex=False).str.strip()
df['price'] = df['price'].str.replace('$','',regex=False).str.replace(',','',regex=False).str.replace('.','',regex=False).str.strip()
df[['price','milage']] = df[['price','milage']].astype('int')

In [66]:
df = df[df['model_year'] >= 2000]

In [73]:
df.duplicated().sum()

np.int64(0)

In [74]:
df['fuel_type'].isnull().sum()
df['fuel_type'].value_counts()
df['fuel_type'].unique()
df[df['fuel_type'].isnull()]
df['fuel_type'] = df['fuel_type'].fillna('unknown')

np.int64(170)

In [87]:
df['accident'].isnull().sum()
df['accident'].unique()
df['accident'].value_counts()
df[df['accident'].isnull()]
df['accident'] = df['accident'].fillna('unknown')
df['accident'] = df['accident'].replace({
    'at least 1 accident or damage reported': 'Yes',
    'none reported': 'No',
    'unknown': 'unknown'
})

np.int64(110)

In [108]:
df['clean_title'].isnull().sum()
df['clean_title'].unique()
df['clean_title'].value_counts()
df[df['clean_title'].isnull()]
df['clean_title'] = df['clean_title'].fillna('unknown')

np.int64(0)

In [114]:
df['brand'].value_counts()
df['brand'].unique()
df['model'].value_counts()
df['model'].unique()

brand
ford             378
bmw              373
mercedes-benz    313
chevrolet        282
audi             200
porsche          196
toyota           192
lexus            160
jeep             138
land             129
nissan           113
cadillac         104
ram               91
gmc               90
dodge             89
tesla             87
kia               76
hyundai           72
subaru            64
honda             62
acura             61
mazda             60
infiniti          59
volkswagen        59
lincoln           52
jaguar            44
volvo             37
maserati          34
bentley           33
mini              33
buick             29
chrysler          28
lamborghini       26
genesis           20
mitsubishi        20
alfa              19
rivian            17
hummer            16
pontiac           13
ferrari           12
rolls-royce       11
aston              9
scion              6
mclaren            6
fiat               5
saturn             5
lotus              4
lucid              3
karma              2
saab               2
mercury            2
bugatti            1
polestar           1
plymouth           1
smart              1
maybach            1
suzuki             1
Name: count, dtype: Int64

In [127]:
df['accident'].value_counts()
df['accident'] = df['accident'].replace({
    'Yes': '1',
    'No': '0',
    'unknown': '0'
})
df['accident'] = df['accident'].astype('int')

accident
0    2975
1     967
Name: count, dtype: Int64

In [133]:
df['clean_title'].value_counts()

df['clean_title'] = df['clean_title'].replace({
    'yes': '1',
    'unknown': '0'
})
df['clean_title'] = df['clean_title'].astype('int')

clean_title
1    3349
0     593
Name: count, dtype: int64

In [154]:
df.drop(columns = ['model'], inplace= True)

KeyError: "['model'] not found in axis"

In [156]:
df.drop(columns = ['engine'], inplace= True)

/tmp/ipykernel_1959/1519853224.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns = ['engine'], inplace= True)

In [151]:
# @title
df['transmission'].value_counts()

df['transmission'].unique()
df['transmission'] = df['transmission'].replace({
    '6-speed a/t': 'automatic',
    '8-speed automatic': 'automatic',
    'automatic': 'automatic',
    '7-speed a/t': 'automatic',
    'f': 'hybrid',
    'a/t': 'automatic',
    '8-speed a/t': 'automatic',
    'transmission w/dual shift mode': 'hybrid',
    '9-speed automatic': 'automatic',
    '6-speed m/t': 'manual',
    '10-speed a/t': 'automatic',
    '9-speed a/t': 'automatic',
    '5-speed a/t': 'automatic',
    '1-speed a/t': 'automatic',
    'automatic cvt': 'automatic',
    '7-speed automatic with auto-shift': 'automatic',
    'cvt-f': 'automatic',
    'm/t': 'manual',
    '6-speed automatic with auto-shift': 'automatic',
    '10-speed automatic': 'automatic',
    'cvt transmission': 'automatic',
    '4-speed a/t': 'automatic',
    '6-speed automatic': 'automatic',
    '4-speed automatic': 'automatic',
    '7-speed m/t': 'manual',
    '8-speed automatic with auto-shift': 'hybrid',
    '5-speed automatic': 'automatic',
    '8-speed at': 'automatic',
    '1-speed automatic': 'automatic',
    '5-speed m/t': 'manual',
    'manual': 'manual',
    '6-speed manual': 'manual',
    'variable': 'manual',
    '2': 'manual',
    '7-speed manual': 'manual',
    'automatic, 9-spd 9g-tronic': 'automatic',
    'automatic, 8-spd': 'automatic',
    'automatic, 8-spd sport w/sport & manual modes': 'automatic',
    '–': 'automatic',
    'auto, 6-spd w/cmdshft': 'automatic',
    'transmission overdrive switch': 'manual',
    '7-speed automatic': 'automatic',
    'automatic, 8-spd pdk dual-clutch': 'automatic',
    'automatic, 8-spd m steptronic w/drivelogic, sport & manual modes': 'hybrid',
    'automatic, 8-spd dual-clutch': 'automatic',
    '6-speed': 'manual',
    'single-speed fixed gear': 'manual',
    'automatic, 10-spd': 'automatic',
    '2-speed automatic': 'automatic',
    '7-speed': 'manual',
    'automatic, 7-spd s tronic dual-clutch': 'automatic',
    'manual, 6-spd': 'manual',
    '6-speed electronically controlled automatic with o': 'automatic',
    '6 speed at/mt': 'hybrid',
    '10-speed automatic with overdrive': 'automatic',
    '7-speed dct automatic': 'automatic',
    '9-speed automatic with auto-shift': 'automatic',
    'scheduled for or in production': 'manual',
    '2-speed a/t': 'automatic',
    '6 speed mt': 'manual',
    '8-speed manual': 'manual'
})

transmission
automatic    3158
hybrid        410
manual        374
Name: count, dtype: Int64

converting label data into numerical data

In [159]:
df = pd.get_dummies(
    df,
    columns=['brand', 'fuel_type', 'transmission'],
    drop_first=True,
    dtype=int
)

KeyError: "None of [Index(['brand', 'fuel_type', 'transmission'], dtype='object')] are in the [columns]"

In [170]:
df.to_csv('used_cars_cleaned.csv', index=False)
files.download('used_cars_cleaned.csv')